#!/bin/bash
# ─────────────────────────────────────────────────────────
# setup-tpm-unlock.sh — Oneshot TPM2 auto-unlock for Arch Linux
# Auto-detects the root LUKS device, configures sd-encrypt,
# creates crypttab.initramfs, fixes kernel cmdline, and enrolls TPM.
# Run AFTER Secure Boot is fully enabled (User/Deployed Mode).
# ─────────────────────────────────────────────────────────
set -euo pipefail

# ── Prereqs ──────────────────────────────────────────────
[[ $EUID -eq 0 ]] || { echo "Run as root: sudo $0"; exit 1; }

for cmd in cryptsetup systemd-cryptenroll mkinitcpio; do
    command -v "$cmd" &>/dev/null || { echo "Missing: $cmd"; exit 1; }
done

echo "══════════════════════════════════════════════════════"
echo " TPM2 Auto-Unlock Setup  (oneshot — fresh Arch)"
echo "══════════════════════════════════════════════════════"
echo ""

# ── Auto-detect root LUKS device ────────────────────────
# Walk: / mount → dm device → backing LUKS partition
ROOT_SRC="$(findmnt -no SOURCE /)"                        # e.g. /dev/mapper/root
if [[ "$ROOT_SRC" == /dev/mapper/* ]]; then
    DM_NAME="${ROOT_SRC##*/}"                              # e.g. root
    LUKS_DEV="$(cryptsetup status "$DM_NAME" 2>/dev/null \
                | awk '/device:/{print $2}')"              # e.g. /dev/nvme0n1p2
else
    echo "Root is not on a dm-crypt device ($ROOT_SRC)."
    echo "Nothing to do."
    exit 1
fi

if [[ -z "$LUKS_DEV" ]] || ! cryptsetup isLuks "$LUKS_DEV" 2>/dev/null; then
    echo "Could not find a LUKS device backing /  (tried $LUKS_DEV)"
    exit 1
fi

LUKS_UUID="$(cryptsetup luksUUID "$LUKS_DEV")"
LUKS_NAME="$DM_NAME"

echo "Detected root encryption:"
echo "  LUKS device : $LUKS_DEV"
echo "  LUKS UUID   : $LUKS_UUID"
echo "  Mapped name : $LUKS_NAME"
echo ""

# ── Secure Boot check ───────────────────────────────────
echo "[1/6] Checking Secure Boot state..."
if command -v sbctl &>/dev/null; then
    sbctl status
    if ! sbctl status 2>/dev/null | grep -q "Secure Boot:.*Enabled"; then
        echo ""
        echo "⚠  Secure Boot is NOT fully enabled."
        echo "   TPM will bind to the CURRENT state — if you enable"
        echo "   Secure Boot later the TPM policy will mismatch."
        echo ""
        read -rp "Continue anyway? [y/N] " -n1; echo
        [[ ${REPLY,,} == y ]] || exit 1
    fi
else
    echo "  sbctl not installed — skipping Secure Boot check."
fi
echo ""

# ── Configure mkinitcpio hooks ──────────────────────────
echo "[2/6] Ensuring systemd-based initramfs hooks..."
MKINIT="/etc/mkinitcpio.conf"
CURRENT_HOOKS="$(grep '^HOOKS=' "$MKINIT")"

# Required: base systemd … sd-vconsole … sd-encrypt
need_change=false
if echo "$CURRENT_HOOKS" | grep -qw udev; then need_change=true; fi
if echo "$CURRENT_HOOKS" | grep -qw keymap; then need_change=true; fi
if echo "$CURRENT_HOOKS" | grep -qw consolefont; then need_change=true; fi
if ! echo "$CURRENT_HOOKS" | grep -qw sd-encrypt; then need_change=true; fi
if ! echo "$CURRENT_HOOKS" | grep -qw systemd; then need_change=true; fi

if $need_change; then
    cp "$MKINIT" "${MKINIT}.backup.$(date +%Y%m%d_%H%M%S)"
    # Replace udev→systemd, keymap+consolefont→sd-vconsole, encrypt→sd-encrypt
    sed -i 's/\budev\b/systemd/g'           "$MKINIT"
    sed -i 's/\bkeymap\b/sd-vconsole/g'     "$MKINIT"
    sed -i 's/\bconsolefont\b//g'            "$MKINIT"
    sed -i 's/\bencrypt\b/sd-encrypt/g'      "$MKINIT"
    # Clean double spaces
    sed -i 's/  \+/ /g; s/( /(/; s/ )/)/;' "$MKINIT"
    echo "  ✓ HOOKS updated:"
    grep '^HOOKS=' "$MKINIT"
else
    echo "  ✓ HOOKS already correct: $CURRENT_HOOKS"
fi
echo ""

# ── Create crypttab.initramfs ───────────────────────────
echo "[3/6] Writing /etc/crypttab.initramfs..."
cat > /etc/crypttab.initramfs << EOF
# <name>       <device>                                     <password>  <options>
$LUKS_NAME     UUID=$LUKS_UUID                               none        tpm2-device=auto
EOF
echo "  ✓ $(cat /etc/crypttab.initramfs | tail -1)"
echo ""

# Also update /etc/crypttab for runtime consistency
if ! grep -q "^$LUKS_NAME" /etc/crypttab 2>/dev/null; then
    echo "# Auto-generated by setup-tpm-unlock.sh" >> /etc/crypttab
    echo "$LUKS_NAME UUID=$LUKS_UUID none tpm2-device=auto" >> /etc/crypttab
    echo "  ✓ Also added entry to /etc/crypttab"
    echo ""
fi

# ── Fix kernel cmdline ──────────────────────────────────
echo "[4/6] Updating /etc/kernel/cmdline for sd-encrypt..."
CMDLINE="/etc/kernel/cmdline"
if [[ -f "$CMDLINE" ]]; then
    cp "$CMDLINE" "${CMDLINE}.backup.$(date +%Y%m%d_%H%M%S)"
    old="$(cat "$CMDLINE")"

    # Strip old-style cryptdevice= and any existing rd.luks.name=
    clean="$(echo "$old" \
        | sed -E 's/(^| )cryptdevice=[^ ]+//g' \
        | sed -E 's/(^| )rd\.luks\.name=[^ ]+//g' \
        | sed -E 's/[[:space:]]+/ /g; s/^ //; s/ $//')"

    new="rd.luks.name=${LUKS_UUID}=${LUKS_NAME} ${clean}"
    printf '%s\n' "$new" > "$CMDLINE"
    echo "  ✓ $CMDLINE updated"
    echo "    $new"
else
    echo "  ⚠ $CMDLINE not found — you may need to update bootloader params manually."
fi
echo ""

# ── Rebuild initramfs / UKI ─────────────────────────────
echo "[5/6] Rebuilding initramfs (and UKI if configured)..."
mkinitcpio -P
echo "  ✓ Initramfs rebuilt"
echo ""

# ── TPM2 enrollment ─────────────────────────────────────
echo "[6/6] Enrolling TPM2 keyslot on $LUKS_DEV..."
echo "  PCR 0 = firmware config,  PCR 7 = Secure Boot state"
echo ""

# Wipe any stale TPM slot first
systemd-cryptenroll "$LUKS_DEV" --wipe-slot=tpm2 2>/dev/null \
    || echo "  (no existing TPM2 slot to remove)"

echo "  Enter the LUKS passphrase when prompted:"
systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=0+7 "$LUKS_DEV"
echo ""
echo "  ✓ TPM2 keyslot enrolled"

# ── Done ─────────────────────────────────────────────────
echo ""
echo "══════════════════════════════════════════════════════"
echo " ✓  TPM2 auto-unlock configured"
echo "══════════════════════════════════════════════════════"
echo ""
echo "Auto-decrypt WILL work when:"
echo "  ✓ Secure Boot is enabled (same state as now)"
echo "  ✓ Firmware config unchanged"
echo ""
echo "Auto-decrypt will FAIL (password required) when:"
echo "  ✗ Secure Boot disabled or mode changed"
echo "  ✗ Firmware/BIOS modified"
echo ""
echo "Test plan:"
echo "  1. Reboot normally    → should auto-unlock (no password)"
echo "  2. Disable Secure Boot → should ask for password"
echo "  3. Re-enable           → should auto-unlock again"
echo ""

read -rp "Reboot now? [y/N] " -n1; echo
[[ ${REPLY,,} == y ]] && { echo "Rebooting in 3s..."; sleep 3; systemctl reboot; }
